language: go

go:
  - 1.11.x

install:
  - go get github.com/stretchr/testify/assert/...

script:
  - go test -race -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - curl -d "repo=github.com/zhoujin7/goback" https://goreportcard.com/checks